### ISSUE TITLE
Render stack:list as tree

### ISSUE THREAD

**Issue by fbrnc** [AOEpeople/StackFormation#10]
Similar to the unix tool `tree`. 
PHP's `RecursiveTreeIterator` could help, but it's not so simple to 1) make it look that nice and be prepare the data in the right format.
Also if a node has only one child it should be flattened (to avoid a large nested hierarchy) - see s3-bucket in the example.

Example:

```
app-dpl-vpc-base
app-dpl-vpc-subnets
app-dpl-setup
app-dpl-deploy-build1
app-dpl-deploy-build2
app-qa-vpc-base
app-qa-vpc-subnets
app-qa-setup
app-qa-deploy-build1
app-qa-deploy-build2
s3-bucket
```

```
.
├── app
│   ├── dpl
│   │   ├── vpc
│   │   │   ├── base
│   │   │   └── subnets
│   │   └── deploy
│   │       ├── build1
│   │       └── build2
│   └── qa
│       ├── vpc
│       │   ├── base
│       │   └── subnets
│       └── deploy
│           ├── build1
│           └── build2
└── s3-bucket
```

**Comment by dng-dev** [comment]
Hi @fbrnc i added a pull request with the "stack:tree" command.
![bildschirmfoto 2016-08-24 um 01 11 17](https://cloud.githubusercontent.com/assets/836079/17913075/e9e9b826-6997-11e6-9a25-2b32f1d1419b.png)

**Comment by kj187** [comment]
Its implemented correct? 
So we can close this issue
