### ISSUE TITLE
Pseudo Parameters are ignored by TemplateManager

### ISSUE THREAD

**Issue by dng-dev** [AOEpeople/StackFormation#29]
During Template Merging Default Pseudo Parameters provided by Amazon are processed.
As Example: if have a Prefix named Az2 and inside the template i use {"Ref": "AWS::Region"}. During the merging process this ref gets transformed to {"Ref": "Az2AWS::Region"}.
[http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html)

**Comment by LeeSaferite** [comment]
I think we need to refactor how this feature works. It's currently a simple set of regex patterns. I think we should parse the template into an array and walk the array looking for the things that need to be modified. We could do a much safer processing this way.

**Comment by dng-dev** [comment]
i have it locally already fixed. Need some more time until we ported all to see its working. Another bug also happen in the same part.
you can define dependsOn : "subnet" which is working when i change it to dependsOn : ["subnet"]  which is an array with 1 element all elements after get the Prefix 2 times. I think we need to improve the regex.

**Comment by dng-dev** [comment]
added pull request #30

**Comment by dng-dev** [comment]
I think we can now close it :)
