### ISSUE TITLE
Support for blueprint references with many ENV vars

### ISSUE THREAD

**Issue by fbrnc** [AOEpeople/StackFormation#8]
When using many ENV vars the blueprint reference (even after gzipping) will be longer than 255 chars exceeding the max value length for tags.

Instead this reference should be injected in the metadata of the template.

**Comment by dng-dev** [comment]
Hey @fbrnc regarding to [this](https://blogs.aws.amazon.com/security/post/Tx3O5RCX34VOGY6/Now-Organize-Your-AWS-Resources-by-Using-up-to-50-Tags-per-Resource) announcement from Amazon this ticket is not required anymore. There seems to be one Exception, i can't see cloudformation in the list.
